DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS income;
DROP TABLE IF EXISTS budget;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS savings;
DROP TABlE IF EXISTS accounts;
DROP TABLE IF EXISTS users;