// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type AccountBalance struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Balance   float64      `json:"balance"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Budget struct {
	ID         int64        `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	BudgetName string       `json:"budget_name"`
	// initial amount must not be greater than account balance
	InitialAmount float64   `json:"initial_amount"`
	CurrentAmount float64   `json:"current_amount"`
	Description   string    `json:"description"`
	StartDate     time.Time `json:"start_date"`
	EndDate       time.Time `json:"end_date"`
	UserID        int64     `json:"user_id"`
}

type Expense struct {
	ID              int64        `json:"id"`
	Amount          float64      `json:"amount"`
	Description     string       `json:"description"`
	ExpenditureDate time.Time    `json:"expenditure_date"`
	Category        string       `json:"category"`
	UserID          int64        `json:"user_id"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}

type Income struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	Amount    float64      `json:"amount"`
	Date      time.Time    `json:"date"`
	UserID    int64        `json:"user_id"`
}

type Saving struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	Amount    float64      `json:"amount"`
	UserID    int64        `json:"user_id"`
}

type Transaction struct {
	ID              int64        `json:"id"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
	Category        string       `json:"category"`
	Amount          float64      `json:"amount"`
	TransactionDate time.Time    `json:"transaction_date"`
	UserID          int64        `json:"user_id"`
}

type User struct {
	ID        int64        `json:"id"`
	Firstname string       `json:"firstname"`
	Lastname  string       `json:"lastname"`
	Email     string       `json:"email"`
	Mobile    string       `json:"mobile"`
	Password  string       `json:"password"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
